// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Pc-sS05o3r9K36z_h1fmfvTyOWMJ9YM',
    appId: '1:46371181115:web:d1d58a22ca6edb9c8dc21e',
    messagingSenderId: '46371181115',
    projectId: 'walmart-e0618',
    authDomain: 'walmart-e0618.firebaseapp.com',
    storageBucket: 'walmart-e0618.firebasestorage.app',
    measurementId: 'G-RNJQ4VP9J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xybV_IFKd9YGsv2DW28bQifuqQ64Ji8',
    appId: '1:46371181115:android:a93618b9a9482a328dc21e',
    messagingSenderId: '46371181115',
    projectId: 'walmart-e0618',
    storageBucket: 'walmart-e0618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTizLIb68y4FARrQkLLu73WT3x2nhSL0E',
    appId: '1:46371181115:ios:a4b7a6db14723d938dc21e',
    messagingSenderId: '46371181115',
    projectId: 'walmart-e0618',
    storageBucket: 'walmart-e0618.firebasestorage.app',
    iosBundleId: 'com.enkasa.walmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTizLIb68y4FARrQkLLu73WT3x2nhSL0E',
    appId: '1:46371181115:ios:a4b7a6db14723d938dc21e',
    messagingSenderId: '46371181115',
    projectId: 'walmart-e0618',
    storageBucket: 'walmart-e0618.firebasestorage.app',
    iosBundleId: 'com.enkasa.walmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Pc-sS05o3r9K36z_h1fmfvTyOWMJ9YM',
    appId: '1:46371181115:web:0399ff874087cf288dc21e',
    messagingSenderId: '46371181115',
    projectId: 'walmart-e0618',
    authDomain: 'walmart-e0618.firebaseapp.com',
    storageBucket: 'walmart-e0618.firebasestorage.app',
    measurementId: 'G-CV3YGPML64',
  );

}